In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('Documents/Org_data.csv.csv')
print (df)

     Research  Operation  Marketing       State     Profit
0   165349.20  136897.80  471784.10    New York  192261.83
1   162597.70  151377.59  443898.53  California  191792.06
2   153441.51  101145.55  407934.54     Florida  191050.39
3   144372.41  118671.85  383199.62    New York  182901.99
4   142107.34   91391.77  366168.42     Florida  166187.94
5   131876.90   99814.71  362861.36    New York  156991.12
6   134615.46  147198.87  127716.82  California  156122.51
7   130298.13  145530.06  323876.68     Florida  155752.60
8   120542.52  148718.95  311613.29    New York  152211.77
9   123334.88  108679.17  304981.62  California  149759.96
10  101913.08  110594.11  229160.95     Florida  146121.95
11  100671.96   91790.61  249744.55  California  144259.40
12   93863.75  127320.38  249839.44     Florida  141585.52
13   91992.39  135495.07  252664.93  California  134307.35
14  119943.24  156547.42  256512.92     Florida  132602.65
15  114523.61  122616.84  261776.23    New York  129917.

In [6]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,4].values
print (X)
print(Y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
dt = ColumnTransformer(transformers=[('one_hot_encoder',OneHotEncoder(categories='auto'),[3])],remainder='passthrough')
X= np.array(dt.fit_transform(X),dtype=np.float)

In [8]:
print(X)

[[0.0000000e+00 0.0000000e+00 1.0000000e+00 1.6534920e+05 1.3689780e+05
  4.7178410e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.6259770e+05 1.5137759e+05
  4.4389853e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.5344151e+05 1.0114555e+05
  4.0793454e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.4437241e+05 1.1867185e+05
  3.8319962e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.4210734e+05 9.1391770e+04
  3.6616842e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.3187690e+05 9.9814710e+04
  3.6286136e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.3461546e+05 1.4719887e+05
  1.2771682e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.3029813e+05 1.4553006e+05
  3.2387668e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.2054252e+05 1.4871895e+05
  3.1161329e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.2333488e+05 1.0867917e+05
  3.0498162e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.0191308e+05 1.1059411e+05
  2.2916095e+05]
 [1.0000000e+00 0.000

In [15]:
X=X[:,1:]
print (X)

[[1.0000000e+00 1.6534920e+05 1.3689780e+05 4.7178410e+05]
 [0.0000000e+00 1.6259770e+05 1.5137759e+05 4.4389853e+05]
 [0.0000000e+00 1.5344151e+05 1.0114555e+05 4.0793454e+05]
 [1.0000000e+00 1.4437241e+05 1.1867185e+05 3.8319962e+05]
 [0.0000000e+00 1.4210734e+05 9.1391770e+04 3.6616842e+05]
 [1.0000000e+00 1.3187690e+05 9.9814710e+04 3.6286136e+05]
 [0.0000000e+00 1.3461546e+05 1.4719887e+05 1.2771682e+05]
 [0.0000000e+00 1.3029813e+05 1.4553006e+05 3.2387668e+05]
 [1.0000000e+00 1.2054252e+05 1.4871895e+05 3.1161329e+05]
 [0.0000000e+00 1.2333488e+05 1.0867917e+05 3.0498162e+05]
 [0.0000000e+00 1.0191308e+05 1.1059411e+05 2.2916095e+05]
 [0.0000000e+00 1.0067196e+05 9.1790610e+04 2.4974455e+05]
 [0.0000000e+00 9.3863750e+04 1.2732038e+05 2.4983944e+05]
 [0.0000000e+00 9.1992390e+04 1.3549507e+05 2.5266493e+05]
 [0.0000000e+00 1.1994324e+05 1.5654742e+05 2.5651292e+05]
 [1.0000000e+00 1.1452361e+05 1.2261684e+05 2.6177623e+05]
 [0.0000000e+00 7.8013110e+04 1.2159755e+05 2.6434606e+0

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20)
print(X_test)
print(X_train)
print(Y_test)
print(Y_train)

[[0.0000000e+00 0.0000000e+00 1.0000000e+00 5.4205000e+02 5.1743150e+04
  0.0000000e+00]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.3029813e+05 1.4553006e+05
  3.2387668e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 3.8558510e+04 8.2982090e+04
  1.7499930e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 6.3408860e+04 1.2921961e+05
  4.6085250e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 6.1994480e+04 1.1564128e+05
  9.1131240e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 2.8663760e+04 1.2705621e+05
  2.0112682e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 6.5605480e+04 1.5303206e+05
  1.0713838e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 7.8013110e+04 1.2159755e+05
  2.6434606e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.4210734e+05 9.1391770e+04
  3.6616842e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 7.5328870e+04 1.4413598e+05
  1.3405007e+05]]
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 7.2107600e+04 1.2786455e+05
  3.5318381e+05]
 [1.0000000e+00 0.00

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
Y_pred = regressor.predict(X_test)
print (Y_pred)

[ 55171.81759517 159611.05315906  84758.72795172 100648.24378137
 102307.59824213  74052.27050687 102411.75893352 115604.24164213
 174696.57216161 111500.73820962]


In [13]:
import statsmodels.formula.api as sm
X= np.append(arr=np.ones((50,1)).astype(int),values=X, axis=1)

In [14]:
print (X)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.6534920e+05
  1.3689780e+05 4.7178410e+05]
 [1.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.6259770e+05
  1.5137759e+05 4.4389853e+05]
 [1.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00 1.5344151e+05
  1.0114555e+05 4.0793454e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.4437241e+05
  1.1867185e+05 3.8319962e+05]
 [1.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00 1.4210734e+05
  9.1391770e+04 3.6616842e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.3187690e+05
  9.9814710e+04 3.6286136e+05]
 [1.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.3461546e+05
  1.4719887e+05 1.2771682e+05]
 [1.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00 1.3029813e+05
  1.4553006e+05 3.2387668e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.2054252e+05
  1.4871895e+05 3.1161329e+05]
 [1.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.2333488e+05
 